name: Feature Tests

on:
  push:
    branches:
      - 1.x
  pull_request:
    branches:
      - 1.x

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        php: [8.1, 8.2, 8.3]
        laravel: [10.*]

    name: OS:${{ matrix.os }} / PHP:${{ matrix.php }} / Laravel:${{ matrix.laravel }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and run tests
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - run: npm install
      - run: npm run lint
      - run: npm run build

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-progress --ansi --no-update
          composer update --no-interaction --no-suggest

      - name: Rector Cache
        uses: actions/cache@v4
        with:
          path: ./var/cache/rector
          key: ${{ runner.os }}-rector-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-rector-

      - name: Pint
        run: ./vendor/bin/pint --test

      - name: Rector
        run: ./vendor/bin/rector process --dry-run --config=rector.php

      - name: PHPStan
        run: ./vendor/bin/phpstan --configuration="phpstan.neon"

      - name: Clear Orchestra Testbench Cache
        run: ./vendor/bin/testbench optimize:clear

      - name: Feature Tests
        run: ./vendor/bin/pest --filter Feature --parallel --order-by random --stop-on-failure
