name: Tests

on:
  push:
    branches:
      - 1.x
  pull_request:
    branches:
      - 1.x
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: [10.*]

    name: PHP:${{ matrix.php }} / Laravel:${{ matrix.laravel }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node and run tests
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - run: npm install
      - run: npm run lint

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          tools: composer:v2
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --no-interaction --no-suggest

      - name: Setup dusk/chrome
        run: vendor/bin/dusk-updater detect --auto-update

      - name: Pint
        run: ./vendor/bin/pint --test

      - name: Feature Tests
        run: ./vendor/bin/pest --filter Feature --parallel

      - name: Browser Tests
        run: ./vendor/bin/pest --filter Browser
        env:
          CI: true

      - name: Upload Failed Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: dusk-fail-screenshots
          path: tests/Browser/screenshots/failure-*
          retention-days: 1

      - name: Upload Failed Console Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: dusk-fail-screenshots
          path: tests/Browser/console/Tests_*
          retention-days: 1
